(()=>{
const $=id=>document.getElementById(id);const selected=new Set();let last=null,lastResidual=null,lastOrder=null;
const PRODUCTS=[['favo-integrale','Favo Integrale Bio'],['polline','Polline Italiano'],['orsetti','Orsetti Gommosi BIO'],['pappa-reale','Pappa Reale Italiana fresca Bio'],['bee-energy','Bee Energy – Tonico BIO'],['propol-active','Propol Active – Compresse BIO'],['propoli-spray','Propoli Spray'],['propoli-alcolica','Propoli alcolica contagocce'],['propoli-analcolica','Propoli analcolica'],['crema-mani','Crema Mani Aloe, Cera d’Api e Propoli'],['burrocacao-propoli-aloe','Burro Cacao Propoli + Aloe'],['burrocacao-miele-pappa','Burro Cacao Miele + Pappa Reale'],['shampoo','Shampoo Propoli e Aloe'],['saponetta-frutti-bosco','Saponetta Frutti di Bosco'],['saponetta-lavanda','Saponetta Lavanda'],['saponetta-aloe','Saponetta Aloe'],['candela-alveare','Candela Alveare'],['limoncello','Limoncello'],['liquore-caffe','Liquore al Caffè'],['castagne-rum','Castagne al Rum']];
const PRODUCT_NAMES=Object.fromEntries(PRODUCTS);const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const identity=()=>({email:$('email').value.trim().toLowerCase(),phone:$('phone').value.trim()});
const shipping=()=>({name:$('shipName').value.trim(),email:$('shipEmail').value.trim().toLowerCase(),phone:$('shipPhone').value.trim(),address:$('shipAddress').value.trim(),postalCode:$('shipPostal').value.trim(),city:$('shipCity').value.trim(),state:$('shipState').value.trim().toUpperCase(),country:$('shipCountry').value.trim()||'Italia',notes:$('shipNotes').value.trim()});
async function api(action,extra={}){const customer=identity();const r=await fetch('/api/bee-wallet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,customer,...extra})});let j={};try{j=await r.json()}catch{}return{r,j}}
function saveIdentity(){localStorage.setItem('beeWalletEmail',$('email').value.trim());localStorage.setItem('beeWalletPhone',$('phone').value.trim())}
function saveShipping(){const s=shipping();localStorage.setItem('beeShipName',s.name);localStorage.setItem('beeShipEmail',s.email);localStorage.setItem('beeShipPhone',s.phone);localStorage.setItem('beeShipAddress',s.address);localStorage.setItem('beeShipPostal',s.postalCode);localStorage.setItem('beeShipCity',s.city);localStorage.setItem('beeShipState',s.state);localStorage.setItem('beeShipCountry',s.country)}
function syncShippingIdentity(){if(!$('shipEmail').value.trim())$('shipEmail').value=$('email').value.trim();if(!$('shipPhone').value.trim())$('shipPhone').value=$('phone').value.trim()}
function shippingValid(){const s=shipping();return !!(s.name&&s.email&&s.email.includes('@')&&s.phone&&s.address&&s.postalCode&&s.city&&s.state)}
function showWallet(j){last=j;$('wallet').hidden=false;const b=Number(j.balance||0);$('balance').textContent=b+' Api';$('bar').style.width=Math.min(100,b)+'%';const unlocked=!!j.rewardUnlocked;$('rewardText').className='msg '+(unlocked?'ok':'');$('rewardText').textContent=unlocked?'🎉 Hai raggiunto 100 Api: puoi ordinare il tuo Cesto dell’Alveare gratuitamente.':'Mancano '+Math.max(0,Number(j.remainingToReward||100-b))+' Api per ottenere il Cesto dell’Alveare.';const credits=Array.isArray(j.credits)?j.credits:[];$('credits').innerHTML=credits.length?'<h3>Crediti attivi</h3>'+credits.map(c=>'<div class="coupon-row"><span><strong>'+esc(c.codeMasked)+'</strong><br><small>'+esc(c.sourceKind==='RESIDUAL'?'Credito residuo':'Coupon Api')+'</small></span><strong>'+Number(c.points||0)+' Api</strong></div>').join(''):'<div class="msg">Nessun credito attivo.</div>';$('reward').hidden=!unlocked;if(!unlocked)selected.clear();syncShippingIdentity();renderGifts()}
async function lookup(){saveIdentity();const {r,j}=await api('lookup');if(!r.ok){$('lookupMsg').className='msg err';$('lookupMsg').textContent='⛔ '+(j.error||'Impossibile leggere il saldo.');return}$('lookupMsg').className='msg ok';$('lookupMsg').textContent=j.found?'✅ Saldo recuperato.':'Nessun saldo precedente: verrà creato quando aggiungi un coupon o fai un acquisto.';showWallet(j)}
function renderGifts(){$('count').textContent=selected.size+' / 5 prodotti scelti';const ready=selected.size===5&&shippingValid();$('claim').disabled=!ready;$('claimMsg').className='msg '+(ready?'ok':'');$('claimMsg').textContent=ready?'✅ Tutto pronto. Conferma l’ordine gratuito del Cesto.':selected.size!==5?'Seleziona ancora '+(5-selected.size)+' '+(5-selected.size===1?'prodotto':'prodotti')+' diversi.':'Completa tutti i dati di spedizione contrassegnati con *.';document.querySelectorAll('.gift').forEach(b=>b.classList.toggle('sel',selected.has(b.dataset.id)))}
function buildGifts(){$('gifts').innerHTML=PRODUCTS.map(([id,n])=>'<button type="button" class="gift" data-id="'+esc(id)+'">'+esc(n)+'</button>').join('');document.querySelectorAll('.gift').forEach(b=>b.onclick=()=>{const id=b.dataset.id;if(selected.has(id))selected.delete(id);else if(selected.size<5)selected.add(id);renderGifts()});renderGifts()}
async function addCoupon(){saveIdentity();const code=$('coupon').value.trim().toUpperCase();if(!code){$('addMsg').className='msg err';$('addMsg').textContent='Inserisci il codice Coupon Api.';return}const {r,j}=await api('add_coupon',{couponCode:code});if(!r.ok){$('addMsg').className='msg err';$('addMsg').textContent='⛔ '+(j.error||'Coupon non utilizzabile.');return}$('addMsg').className='msg ok';$('addMsg').textContent=j.alreadyInBalance?'✅ Questo coupon è già collegato al tuo saldo.':'✅ Coupon valido: +'+Number(j.pointsAdded||j.couponPoints||0)+' Api. Nuovo saldo '+Number(j.balance||0)+' Api.';$('coupon').value='';showWallet(j)}
function couponText(code,points,label){return 'LA FABBRICA DELLE API\n'+(label||'COUPON API')+'\n\nCODICE: '+code+'\nVALORE: '+points+' API\nSTATO: ATTIVO\nSCADENZA: NESSUNA\n\nConserva questo codice. Le Api restano valide fino al loro utilizzo per il Cesto dell’Alveare.'}
function downloadCoupon(code,points,label){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([couponText(code,points,label)],{type:'text/plain;charset=utf-8'}));a.download='Coupon_Api_'+code.replace(/[^A-Z0-9-]/gi,'_')+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function printCoupon(code,points,label){const w=open('','_blank','width=700,height=700');if(!w)return;w.document.write('<!doctype html><html><head><title>Coupon Api</title><style>body{font-family:Arial;padding:40px;text-align:center}.box{border:4px solid #d4a72c;border-radius:24px;padding:32px}.code{font:900 30px monospace;margin:24px 0}.pts{font-size:28px;font-weight:900}</style></head><body><div class="box"><h1>🐝 LA FABBRICA DELLE API</h1><h2>'+esc(label||'COUPON API')+'</h2><div class="code">'+esc(code)+'</div><div class="pts">'+Number(points)+' API</div><p><strong>NESSUNA SCADENZA</strong></p><p>Conserva questo codice. Le Api restano valide fino al loro utilizzo per il Cesto dell’Alveare.</p></div></body></html>');w.document.close();w.onload=()=>w.print()}
function orderText(o){const names=(o.giftProducts||[]).map(id=>PRODUCT_NAMES[id]||id);return ['LA FABBRICA DELLE API','ORDINE CESTO DELL’ALVEARE','',o.orderNumber,'Stato: '+o.status,'','Cliente: '+o.customerName,'Email: '+o.email,'Telefono: '+o.phone,'Spedizione: '+o.address+', '+o.postalCode+' '+o.city+' ('+o.state+') - '+o.country,'','Prodotti:',...names.map((n,i)=>(i+1)+'. '+n),'','Pagamento: 100 Api','Spedizione: €0,00','Totale da pagare: €0,00','',"Ordine ricevuto correttamente. Non è richiesto alcun pagamento."].join('\n')}
function renderOrder(o){lastOrder=o;$('orderConfirmation').hidden=false;$('orderNumber').textContent=o.orderNumber;$('orderStatus').textContent=o.status||'DA PREPARARE';$('orderProducts').innerHTML=(o.giftProducts||[]).map((id,i)=>(i+1)+'. '+esc(PRODUCT_NAMES[id]||id)).join('<br>');$('orderShipping').innerHTML='<strong>'+esc(o.customerName)+'</strong><br>'+esc(o.address)+'<br>'+esc(o.postalCode)+' '+esc(o.city)+' ('+esc(o.state)+') · '+esc(o.country)+'<br>'+esc(o.email)+' · '+esc(o.phone)+(o.notes?'<br><small>Note: '+esc(o.notes)+'</small>':'');localStorage.setItem('beeLastCestoOrder',JSON.stringify(o));$('orderConfirmation').scrollIntoView({behavior:'smooth',block:'start'})}
function printOrder(o){if(!o)return;const w=open('','_blank','width=760,height=850');if(!w)return;const names=(o.giftProducts||[]).map(id=>PRODUCT_NAMES[id]||id);w.document.write('<!doctype html><html><head><title>'+esc(o.orderNumber)+'</title><style>body{font-family:Arial;padding:36px;color:#111}.box{border:3px solid #15803d;border-radius:18px;padding:26px}h1{color:#92400e}.num{font:900 26px monospace}.row{padding:8px 0;border-bottom:1px solid #ddd}.free{font-size:22px;font-weight:900;color:#15803d}</style></head><body><div class="box"><h1>🐝 LA FABBRICA DELLE API</h1><h2>ORDINE CESTO CONFERMATO</h2><div class="num">'+esc(o.orderNumber)+'</div><p><strong>Stato:</strong> '+esc(o.status)+'</p><h3>Cliente e spedizione</h3><p><strong>'+esc(o.customerName)+'</strong><br>'+esc(o.address)+'<br>'+esc(o.postalCode)+' '+esc(o.city)+' ('+esc(o.state)+') - '+esc(o.country)+'<br>'+esc(o.email)+' · '+esc(o.phone)+'</p><h3>5 prodotti</h3><ol>'+names.map(n=>'<li>'+esc(n)+'</li>').join('')+'</ol><div class="row"><strong>Pagamento:</strong> 100 Api</div><div class="row"><strong>Spedizione:</strong> €0,00</div><div class="row"><strong>Totale da pagare:</strong> <span class="free">€0,00</span></div><p><strong>Non devi effettuare alcun pagamento. La spedizione è compresa.</strong></p></div></body></html>');w.document.close();w.onload=()=>w.print()}
function downloadOrder(o){if(!o)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([orderText(o)],{type:'text/plain;charset=utf-8'}));a.download='Ordine_'+String(o.orderNumber).replace(/[^A-Z0-9-]/gi,'_')+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function claim(){if(selected.size!==5){renderGifts();return}if(!shippingValid()){renderGifts();$('claimMsg').className='msg err';$('claimMsg').textContent='⛔ Completa nome, email, telefono e indirizzo di spedizione.';return}saveIdentity();saveShipping();const btn=$('claim');btn.disabled=true;btn.textContent='Creazione ordine in corso...';const {r,j}=await api('claim',{giftProducts:[...selected],shipping:shipping()});if(!r.ok){$('claimMsg').className='msg err';$('claimMsg').textContent='⛔ '+(j.error||'Impossibile creare l’ordine Cesto.');btn.disabled=false;btn.textContent='✅ CONFERMA ORDINE CESTO — €0,00';return}selected.clear();showWallet(j);$('reward').hidden=true;$('claimMsg').className='msg ok';$('claimMsg').textContent='✅ Ordine Cesto creato correttamente.';if(j.cestoOrder)renderOrder(j.cestoOrder);if(j.residualCoupon){lastResidual=j.residualCoupon;$('residual').hidden=false;$('residualCode').textContent=j.residualCoupon.code;$('residualPoints').textContent=j.residualCoupon.points+' Api'}else{$('residual').hidden=true;lastResidual=null}}
$('lookup').onclick=lookup;$('add').onclick=addCoupon;$('claim').onclick=claim;$('printResidual').onclick=()=>lastResidual&&printCoupon(lastResidual.code,lastResidual.points,'CREDITO API RESIDUO');$('downloadResidual').onclick=()=>lastResidual&&downloadCoupon(lastResidual.code,lastResidual.points,'CREDITO API RESIDUO');$('printOrder').onclick=()=>printOrder(lastOrder);$('downloadOrder').onclick=()=>downloadOrder(lastOrder);
$('email').value=localStorage.getItem('beeWalletEmail')||'';$('phone').value=localStorage.getItem('beeWalletPhone')||'';$('shipName').value=localStorage.getItem('beeShipName')||'';$('shipEmail').value=localStorage.getItem('beeShipEmail')||$('email').value;$('shipPhone').value=localStorage.getItem('beeShipPhone')||$('phone').value;$('shipAddress').value=localStorage.getItem('beeShipAddress')||'';$('shipPostal').value=localStorage.getItem('beeShipPostal')||'';$('shipCity').value=localStorage.getItem('beeShipCity')||'';$('shipState').value=localStorage.getItem('beeShipState')||'';$('shipCountry').value=localStorage.getItem('beeShipCountry')||'Italia';
['shipName','shipEmail','shipPhone','shipAddress','shipPostal','shipCity','shipState','shipCountry','shipNotes'].forEach(id=>$(id).addEventListener('input',renderGifts));$('email').addEventListener('input',()=>{if(!$('shipEmail').value.trim())$('shipEmail').value=$('email').value.trim()});$('phone').addEventListener('input',()=>{if(!$('shipPhone').value.trim())$('shipPhone').value=$('phone').value.trim()});
try{const stored=JSON.parse(localStorage.getItem('beeLastCestoOrder')||'null');if(stored&&stored.orderNumber)lastOrder=stored}catch{}
buildGifts();
})();
