(()=>{const $=id=>document.getElementById(id);const selected=new Set();let last=null,lastResidual=null;const PRODUCTS=[['favo-integrale','Favo Integrale Bio'],['polline','Polline Italiano'],['orsetti','Orsetti Gommosi BIO'],['pappa-reale','Pappa Reale Italiana fresca Bio'],['bee-energy','Bee Energy – Tonico BIO'],['propol-active','Propol Active – Compresse BIO'],['propoli-spray','Propoli Spray'],['propoli-alcolica','Propoli alcolica contagocce'],['propoli-analcolica','Propoli analcolica'],['crema-mani','Crema Mani Aloe, Cera d’Api e Propoli'],['burrocacao-propoli-aloe','Burro Cacao Propoli + Aloe'],['burrocacao-miele-pappa','Burro Cacao Miele + Pappa Reale'],['shampoo','Shampoo Propoli e Aloe'],['saponetta-frutti-bosco','Saponetta Frutti di Bosco'],['saponetta-lavanda','Saponetta Lavanda'],['saponetta-aloe','Saponetta Aloe'],['candela-alveare','Candela Alveare'],['limoncello','Limoncello'],['liquore-caffe','Liquore al Caffè'],['castagne-rum','Castagne al Rum']];
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const identity=()=>({email:$('email').value.trim().toLowerCase(),phone:$('phone').value.trim()});
async function api(action,extra={}){const customer=identity();const r=await fetch('/api/bee-wallet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,customer,...extra})});let j={};try{j=await r.json()}catch{}return{r,j}}
function saveIdentity(){localStorage.setItem('beeWalletEmail',$('email').value.trim());localStorage.setItem('beeWalletPhone',$('phone').value.trim())}
function showWallet(j){last=j;$('wallet').hidden=false;const b=Number(j.balance||0);$('balance').textContent=b+' Api';$('bar').style.width=Math.min(100,b)+'%';const unlocked=!!j.rewardUnlocked;$('rewardText').className='msg '+(unlocked?'ok':'');$('rewardText').textContent=unlocked?'🎉 Hai raggiunto 100 Api: puoi comporre il tuo Cesto dell’Alveare.':'Mancano '+Math.max(0,Number(j.remainingToReward||100-b))+' Api per ottenere il Cesto dell’Alveare.';const credits=Array.isArray(j.credits)?j.credits:[];$('credits').innerHTML=credits.length?'<h3>Crediti attivi</h3>'+credits.map(c=>'<div class="coupon-row"><span><strong>'+esc(c.codeMasked)+'</strong><br><small>'+esc(c.sourceKind==='RESIDUAL'?'Credito residuo':'Coupon Api')+'</small></span><strong>'+Number(c.points||0)+' Api</strong></div>').join(''):'<div class="msg">Nessun credito attivo.</div>';$('reward').hidden=!unlocked;if(!unlocked)selected.clear();renderGifts()}
async function lookup(){saveIdentity();const {r,j}=await api('lookup');if(!r.ok){$('lookupMsg').className='msg err';$('lookupMsg').textContent='⛔ '+(j.error||'Impossibile leggere il saldo.');return}$('lookupMsg').className='msg ok';$('lookupMsg').textContent=j.found?'✅ Saldo recuperato.':'Nessun saldo precedente: verrà creato quando aggiungi un coupon o fai un acquisto.';showWallet(j)}
function renderGifts(){$('count').textContent=selected.size+' / 5 prodotti scelti';$('claim').disabled=selected.size!==5;$('claimMsg').className='msg '+(selected.size===5?'ok':'');$('claimMsg').textContent=selected.size===5?'✅ Hai scelto 5 prodotti diversi. Ora puoi proseguire e ritirare il Cesto.':'Seleziona ancora '+(5-selected.size)+' '+(5-selected.size===1?'prodotto':'prodotti')+' diversi.';document.querySelectorAll('.gift').forEach(b=>b.classList.toggle('sel',selected.has(b.dataset.id)))}
function buildGifts(){$('gifts').innerHTML=PRODUCTS.map(([id,n])=>'<button type="button" class="gift" data-id="'+esc(id)+'">'+esc(n)+'</button>').join('');document.querySelectorAll('.gift').forEach(b=>b.onclick=()=>{const id=b.dataset.id;if(selected.has(id))selected.delete(id);else if(selected.size<5)selected.add(id);renderGifts()});renderGifts()}
async function addCoupon(){saveIdentity();const code=$('coupon').value.trim().toUpperCase();if(!code){$('addMsg').className='msg err';$('addMsg').textContent='Inserisci il codice Coupon Api.';return}const {r,j}=await api('add_coupon',{couponCode:code});if(!r.ok){$('addMsg').className='msg err';$('addMsg').textContent='⛔ '+(j.error||'Coupon non utilizzabile.');return}$('addMsg').className='msg ok';$('addMsg').textContent=j.alreadyInBalance?'✅ Questo coupon è già collegato al tuo saldo.':'✅ Coupon valido: +'+Number(j.pointsAdded||j.couponPoints||0)+' Api. Nuovo saldo '+Number(j.balance||0)+' Api.';$('coupon').value='';showWallet(j)}
function couponText(code,points,label){return 'LA FABBRICA DELLE API\n'+(label||'COUPON API')+'\n\nCODICE: '+code+'\nVALORE: '+points+' API\nSTATO: ATTIVO\nSCADENZA: NESSUNA\n\nConserva questo codice. Le Api restano valide fino al loro utilizzo per il Cesto dell’Alveare.'}
function downloadCoupon(code,points,label){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([couponText(code,points,label)],{type:'text/plain;charset=utf-8'}));a.download='Coupon_Api_'+code.replace(/[^A-Z0-9-]/gi,'_')+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function printCoupon(code,points,label){const w=open('','_blank','width=700,height=700');if(!w)return;w.document.write('<!doctype html><html><head><title>Coupon Api</title><style>body{font-family:Arial;padding:40px;text-align:center}.box{border:4px solid #d4a72c;border-radius:24px;padding:32px}.code{font:900 30px monospace;margin:24px 0}.pts{font-size:28px;font-weight:900}</style></head><body><div class="box"><h1>🐝 LA FABBRICA DELLE API</h1><h2>'+esc(label||'COUPON API')+'</h2><div class="code">'+esc(code)+'</div><div class="pts">'+Number(points)+' API</div><p><strong>NESSUNA SCADENZA</strong></p><p>Conserva questo codice. Le Api restano valide fino al loro utilizzo per il Cesto dell’Alveare.</p></div></body></html>');w.document.close();w.onload=()=>w.print()}
async function claim(){if(selected.size!==5)return;const btn=$('claim');btn.disabled=true;btn.textContent='Ritiro in corso...';const {r,j}=await api('claim',{giftProducts:[...selected]});if(!r.ok){$('claimMsg').className='msg err';$('claimMsg').textContent='⛔ '+(j.error||'Impossibile ritirare il Cesto.');btn.disabled=false;btn.textContent='Prosegui e ritira il Cesto';return}selected.clear();showWallet(j);$('reward').hidden=true;$('claimMsg').className='msg ok';$('claimMsg').textContent='🎁 Cesto confermato. 100 Api utilizzate.';if(j.residualCoupon){lastResidual=j.residualCoupon;$('residual').hidden=false;$('residualCode').textContent=j.residualCoupon.code;$('residualPoints').textContent=j.residualCoupon.points+' Api'}else{$('residual').hidden=true;lastResidual=null}$('wallet').scrollIntoView({behavior:'smooth',block:'center'})}
$('lookup').onclick=lookup;$('add').onclick=addCoupon;$('claim').onclick=claim;$('printResidual').onclick=()=>lastResidual&&printCoupon(lastResidual.code,lastResidual.points,'CREDITO API RESIDUO');$('downloadResidual').onclick=()=>lastResidual&&downloadCoupon(lastResidual.code,lastResidual.points,'CREDITO API RESIDUO');$('email').value=localStorage.getItem('beeWalletEmail')||'';$('phone').value=localStorage.getItem('beeWalletPhone')||'';buildGifts();})();